version: "3"
services:
  node1:
    build: .
    container_name: node1
    networks:
      - mpi_network
  node2:
    build: .
    container_name: node2
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge
